### ISSUE TITLE
Installation of v0.6 fails on Ubuntu

### ISSUE THREAD

**Issue by StuartBayley** [jmaupetit/md2pdf#48]
I'm seeing a problem with the v0.6 package from pypi when I try to install it on Ubuntu. 

Here is the output:
```
(.venv) ubuntu@nano:~/MD2PDF/Test$ pip install md2pdf
Collecting md2pdf
  Using cached md2pdf-0.6.tar.gz (6.2 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-tg3p4glh/md2pdf_53aa8b8666c04ce0abe6fcc93717a830/setup.py", line 7, in <module>
          import md2pdf
        File "/tmp/pip-install-tg3p4glh/md2pdf_53aa8b8666c04ce0abe6fcc93717a830/md2pdf/__init__.py", line 8, in <module>
          from md2pdf.core import md2pdf  # noqa
        File "/tmp/pip-install-tg3p4glh/md2pdf_53aa8b8666c04ce0abe6fcc93717a830/md2pdf/core.py", line 4, in <module>
          from markdown2 import markdown, markdown_path
      ModuleNotFoundError: No module named 'markdown2'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Here is some info about the environment:
```
(.venv) ubuntu@nano:~/MD2PDF/Test$ grep VERSION  /etc/os-release 
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
(.venv) ubuntu@nano:~/MD2PDF/Test$ python --version
Python 3.10.6
(.venv) ubuntu@nano:~/MD2PDF/Test$ pip list
Package    Version
---------- -------
pip        22.0.2
setuptools 59.6.0
```

I see the same error after upgrading to pip 23.0.1 and setuptools 67.6.1, which are the latest available.

**Comment by jmaupetit** [comment]
Thanks for the report, it can reproduce it!

**Comment by jmaupetit** [comment]
Looks like I failed. :sweat:
